# Generated by Django 5.1.2 on 2024-10-19 17:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CausaMuerte',
            fields=[
                ('id_causa_muerte', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_causa', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id_hospital', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_hospital', models.CharField(max_length=100)),
                ('comuna', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='InformeMuerteHospitalaria',
            fields=[
                ('id_informe', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_paciente', models.CharField(max_length=100)),
                ('rut_paciente', models.IntegerField()),
                ('dv', models.CharField(max_length=1)),
                ('causa_muerte', models.CharField(max_length=50)),
                ('rut_medico', models.CharField(max_length=10)),
                ('nombre_medico', models.CharField(max_length=100)),
                ('nombre_hospital', models.CharField(max_length=100)),
                ('fecha_muerte', models.DateField()),
                ('detalles_muerte', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('rut_medico', models.IntegerField(primary_key=True, serialize=False)),
                ('dv', models.CharField(max_length=1)),
                ('nombre', models.CharField(max_length=100)),
                ('especialidad', models.CharField(blank=True, max_length=50, null=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='muertes_hospitalarias.hospital')),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('rut_paciente', models.IntegerField(primary_key=True, serialize=False)),
                ('dv', models.CharField(max_length=1)),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('fecha_muerte', models.DateField(blank=True, null=True)),
                ('hora_muerte', models.TimeField(blank=True, null=True)),
                ('detalles_muerte', models.CharField(blank=True, max_length=255, null=True)),
                ('causa_muerte', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='muertes_hospitalarias.causamuerte')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='muertes_hospitalarias.hospital')),
                ('medico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='muertes_hospitalarias.medico')),
            ],
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
