# Generated by Django 5.1.2 on 2024-10-19 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muertes_hospitalarias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='genero',
            field=models.CharField(choices=[('masculino', 'Masculino'), ('femenino', 'Femenino'), ('otro', 'Otro')], default='masculino', max_length=10),
        ),
    ]
