# Generated by Django 5.1.2 on 2024-10-20 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('muertes_hospitalarias', '0002_ciudad_comuna_alter_hospital_comuna'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='ciudad',
        ),
    ]
