# Generated by Django 5.1.2 on 2024-10-20 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muertes_hospitalarias', '0003_remove_hospital_ciudad'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='ciudad',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
