# Generated by Django 5.1.2 on 2024-10-21 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muertes_hospitalarias', '0006_alerta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='informemuertehospitalaria',
            name='nombre_hospital',
        ),
        migrations.AddField(
            model_name='informemuertehospitalaria',
            name='edad_muerte',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='informemuertehospitalaria',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='informemuertehospitalaria',
            name='genero',
            field=models.CharField(choices=[('masculino', 'Masculino'), ('femenino', 'Femenino'), ('otro', 'Otro')], default='masculino', max_length=10),
        ),
        migrations.AddField(
            model_name='informemuertehospitalaria',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='muertes_hospitalarias.hospital'),
        ),
        migrations.AddField(
            model_name='informemuertehospitalaria',
            name='region_hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='muertes_hospitalarias.region'),
        ),
    ]
